import * as Print from "expo-print";
import * as FileSystem from "expo-file-system/legacy";
import { formatDateKey, formatTimestamp } from "./dateUtils";
import { Record, Photo } from "../db/database";

export async function generatePDF(
  record: Record,
  photos: Photo[],
  photoUris: string[]
): Promise<string> {
  const dateStr = formatDateKey(record.dateKey);
  const timestampStr = formatTimestamp(record.createdAt);

  let imagesHtml = "";
  for (let i = 0; i < photos.length; i++) {
    const photo = photos[i];
    const base64 = await FileSystem.readAsStringAsync(photo.fileUri, {
      encoding: FileSystem.EncodingType.Base64,
    });
    const mimeType = photo.mimeType || "image/jpeg";
    imagesHtml += `
      <div style="margin: 20px 0; text-align: center;">
        <img src="data:${mimeType};base64,${base64}" style="max-width: 100%; height: auto; page-break-inside: avoid;" />
      </div>
    `;
  }

  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <style>
          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            max-width: 800px;
            margin: 40px auto;
            padding: 20px;
            color: #333;
          }
          h1 {
            color: #000;
            border-bottom: 2px solid #000;
            padding-bottom: 10px;
            margin-bottom: 30px;
          }
          .section {
            margin: 20px 0;
          }
          .label {
            font-weight: 600;
            color: #666;
            font-size: 14px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
          }
          .value {
            margin-top: 5px;
            font-size: 16px;
            line-height: 1.6;
          }
          .note {
            white-space: pre-wrap;
            background: #f5f5f5;
            padding: 15px;
            border-radius: 4px;
            margin: 10px 0;
          }
          .hash {
            font-family: 'Courier New', monospace;
            font-size: 12px;
            word-break: break-all;
            background: #f5f5f5;
            padding: 10px;
            border-radius: 4px;
            margin: 10px 0;
          }
          .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            font-size: 12px;
            color: #666;
            text-align: center;
          }
        </style>
      </head>
      <body>
        <h1>Proof Record</h1>
        
        <div class="section">
          <div class="label">Date</div>
          <div class="value">${dateStr}</div>
        </div>

        <div class="section">
          <div class="label">Created At</div>
          <div class="value">${timestampStr}</div>
        </div>

        ${
          record.note
            ? `
        <div class="section">
          <div class="label">Note</div>
          <div class="value note">${escapeHtml(record.note)}</div>
        </div>
        `
            : ""
        }

        ${
          photos.length > 0
            ? `
        <div class="section">
          <div class="label">Photos (${photos.length})</div>
          ${imagesHtml}
        </div>
        `
            : ""
        }

        <div class="section">
          <div class="label">Integrity Hash (SHA-256)</div>
          <div class="value hash">${record.recordHash}</div>
        </div>

        <div class="footer">
          Generated by Proof (offline, local-only)
        </div>
      </body>
    </html>
  `;

  const { uri } = await Print.printToFileAsync({ html });
  return uri;
}

export async function sharePDF(
  pdfUri: string,
  dateKey: string
): Promise<string> {
  const fileName = `proof-${dateKey}.pdf`;
  const newUri = FileSystem.documentDirectory + fileName;

  // Copy to a more accessible location with proper name
  await FileSystem.copyAsync({
    from: pdfUri,
    to: newUri,
  });

  return newUri;
}

function escapeHtml(text: string): string {
  const map: { [key: string]: string } = {
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&#039;",
  };
  return text.replace(/[&<>"']/g, (m) => map[m]);
}
